### ISSUE TITLE
BUG: links filter does not work properly

### ISSUE THREAD

**Issue by maxschoe149** [JanMStraub/ITA-Twitter_Analytics#1]
produces 2 links in 1 item or faulty(uncomplete) links

EXAMPLE:

"links": {
        "https://t.co/vTm0Mm": 19,
        "https://t.co/tzx9bHvNLl": 1,
        "https://t.co/af0xCB6KDC": 1,
        "https://t.co/KbEOTWU3K6": 16,
        "https://t.co/Xz7jGq5J4N": 1,
        "https://t.co/zjCo4yW020": 1,
        "https://t.co/jyWGuTTMIk": 1,
        "https://t.co/kXyhG7Zy1J": 22,
        "https://t.co/L5Mz2xLRqt": 202,
        "https://t.co/ohGjRCZZjo https://t.c": 11,
        "https://t.co/LzbW41lpMO": 1,
        "https://t.co/G7YyYgIUfQ": 1,
        "https://t.co/JGZDbzh1om": 1,
        "https://t.co/QCwOzTg5QH": 1,
        "https://t.co/xhZY2kqYD3": 1,
        "https://t.co/uSNzvsIb9a": 1,
        "https://t.co/3nZtCNcyeH": 1,
        "https://t.co/94nsgNwXCC": 1,
        "https://t.co/3vABucQxVp": 9,
        "https://t.co/rWUVJpaltK": 2,
        "https://t.c": 5,
        "https://t.co/0UGtNXCdrs": 1,
        "https://t.co/18wAwGSHgT": 1,
        "https://t.co/6Bxf4ITai2": 1,
        "https://t.co/BG22wVxI4f": 1,
        "https://t.co/adaRUd78pt": 1,
        "https://t.co/0lFct59FCv": 36,
        "https://t.co/9npdVoY9dC": 1,
        "https://t.co/qSwdW2PMVn https://t.co/ryfcgolChE": 1,
        "https://t.co/qSwdW2PMVn https://t.co/TjL9j4V4y4": 1,
        "https://t.co/GiCYdYHxjO": 1,
        "https://t.co/qSwdW2PMVn": 1,
        "https://t.co/jxiR16h7z8": 1,
        "https://t.co/Sbdb6GkNiJ": 1,
        "https://t.co/2QYV3hgf5z": 1,
        "https://t.co/Sbdb6GCoah": 1,
        "https://t.co/JpL7Nu6plr": 1,
        "https://t.co/WuUZq6ee4w": 1,
        "https://t.co/FDZFBeNIpw": 1,
        "https://t.co/h6XKxCXRrP https://t.co/Igg4WUnXSN": 1,
        "https://t.co/M1XPJ86Fma": 1,
        "https://t.co/N43Y7QWqtl": 1,
        "https://t.co/SNQw2k00fq": 1,
        "https://t.co/t4D8dD2rMO": 1,
        "https://t.co/nPYIda5dYW": 1,
        "https://t.co/LOzRNZM1Ar": 1,
        "https://t.co/XvrjF85YgW": 1,
        "https://t.co/IAYn7bYPnF": 1,
        "https://t.co/sCjroLIzOt": 1,
        "https://t.co/vpzqhEfXyi": 2,
        "https://t.co/mkOXC0OcJA": 1,
        "https://t.co/yXf9b3Dfgl": 1,
        "https://t.co/5kH6SAmaTf": 1,
        "https://t.co/kmeqoEHnF3": 1,
        "https://t.co/xv1CRGEuVw": 1,
        "https://t.co/lmTwPic5Xv": 1,
        "https://t.co/zi9qBZKzpd": 1,
        "https://t.co/pQBZnjlTRc": 1,
        "https://t.co/quKkt7wWVD": 1,
        "https://t.co/Aqn9CATHu2": 1,
        "https://t.co/MMUQsN7HOW": 1,
        "https://t.co/UXDNZwQjTY": 5,
        "https://t.co/IkGQm7JTvw https://t.co/vDQrdpcGSJ": 1,
        "https://t.co/Te1lTWIKHI": 1,
        "https://t.co/3CXs6xeZWG": 1,
        "https://t.co/lHPS8KPO3u": 1,
        "https://t.co/yPMe2rWDGr": 1,
        "https://t.co/ltPb3Qjbti": 3,
        "https://t.co/s1eGEHvOJk": 5,
        "https://t.co/8Bxe5KoidB": 1,
        "https://t.co/pK338jjm51": 1,
        "https://t.co/V6vHxtP2Vy": 1,
        "https://t.co/TGp0Bzm6FD https://t.co/zU0heH5kHA": 1,
        "https://t.co/Bch0acy2CW": 2,
        "https://t.co/fk4Vq1DjYW": 1,
        "https://t.co/SjblD5Wtw7": 4,
        "https://t.co/bIkNBtBy3T": 1,
        "https://t.co/6c6WbqdteF": 1,
        "https://t.co/4Gj3yLQYkP": 2,
        "https://t.co/7OJW22pBoo": 1,
        "https://t.co/lBxiCi6yNA": 13,
        "https://t.co/iEBZO0QQdc": 1,
        "https://t.co/RM4y2jjcmf": 1,
        "https://t.co/4FsBrLgnTF": 1,
        "https://t.co/ohGjRCZZjo https://t.co/xlBclP3fcw": 1,
        "https://t.co/wZ4popHLVk": 2,
        "https://t.co/krD7Ba0Mbg": 1,
        "https://t.co/Q6kav3MQeU": 1,
        "https://t.co/Rvw0mDvjEw": 1,
        "https://t.co/aiczlEetct": 1,
        "https://t.co/pSRWskyRXZ": 1,
        "https://t.co/ZwOSawBkHy": 1,
        "https://t.co/ivVMApZXja": 1,
        "https://t.co/mdlmXRn2pS": 1,
        "https://t.co/8Ym1wuIXkx": 1,
        "https://t.co/apYUEaUwZu": 1,
        "https://t.co/XYimLXRDAq": 1,
        "https://t.co/dIfC2n15hM": 1,
        "https://t.co/PCgJpb98va": 1,
        "https://t.co/O1LsbTxxHN": 1,
        "https://t.co/U7kpGvwZ9f": 1,
        "https://t.co/itHzznNvYB": 1,
        "https://t.co/iFEK0xox4i": 1,
        "https://t.co/bx4vxk6Pe4": 1,
        "https://t.co/KjpYf84G4t": 1,
        "https://t.co/WYznFnzf6T": 1,
        "https://t.co/ZnVu7zX4N5 https://t.co/zHs6odW446": 1,
        "https://t.co/": 1,
        "https://t.co/e7IGQj52Zo https://t.co/xSKZBrlGI6": 1,
        "https://t.co/EE3dejrmaO": 1,
        "https://t.co/fywky3UCBQ": 1,
        "https://t.co/kUejkHGFNl": 1,
        "https://t.co/WwDMquiELF": 1,
        "https://t.co/SldEYCPINl": 1,
        "https://t.co/TTdxv7QfZm": 1,
        "https://t.co/jz0xFHpSdC": 1,
        "https://t.co/qvIHREOsoR": 1,
        "https://t.co/yeSxZMWjuB": 1,
        "https://t.co/3i8yz4p8XA": 1,
        "https://t.co/F4kfadSTZf": 1,
        "https://t.co/sLy8P360Zi": 1,
        "https://t.co/KIADgQdSFn": 1,
        "https://t.co/lTLlrrn50d": 1,
        "https://t.co/fYhTKhjR6b": 1,
        "https://t.co/uRGzhtCajw": 1,
        "https://t.co/2woUWsKhkN": 1,
        "https://t.co/vTm0MmuI0a": 1,
        "https://t.co/4W0y3H3AvQ": 1,
        "https://t.co/2rWqjkhQ8g": 1,
        "https://t.co/V65q0S5Y0t": 1,
        "https://t.co/vP26bVD3eT": 1,
        "https://t.co/YKvLXE10BR": 1,
        "https://t.co/IznEsxafuU": 1,
        "https://t.co/O9lCcHqjqC": 1,
        "https://t.co/3lzejzXlSA": 1,
        "https://t.co/2bcadlGDF5": 1,
        "https://t.co/hsHTFQNwXd": 1,
        "https://t.co/AUgOY9C0s2": 1,
        "https://t.co/8SGnVwC6pr https://t.co/zlhcnFmi7B": 1,
        "https://t.co/a7ujnQhpVz": 1,
        "https://t.co/lduxKBApa4": 1,
        "https://t.co/WziL4A5Bzr": 1,
        "https://www..welt.de/politik/plus224367844/Quarantaenebrecher-Laender-schaffen-Zentralstellen-zur-Zwangseinweisung.html": 1,
        "https://t.co/Cu1nGhWc2R": 1,
        "https://t.co/IAwp2fJplY": 1,
        "https://t.co/zRhKCvqQg5": 1,
        "https://t.co/F2PD7V46vB": 1,
        "https://t.co/fpu0caEpLY": 1,
        "https://t.co/IkrnZBF3jj": 1,
        "https://t.co/vtUvOKsnMe": 1,
        "https://t.co/b3QCUoljQS": 1,
        "https://t.co/OSholXt6n1": 1,

**Comment by JanMStraub** [comment]
fixed it

**Comment by maxschoe149** [comment]
STILL DOES NOT WORK PROPERLY
{"https://twitter.com/Dominik33/status/1354868018623508484/video/1": 14, "https://twitter.com/BB12_DE/status/1357099603829477376/photo/1": 10,
 "https://t.co/ymEBe": 9,
 "https://twitter.com/BB12_DE/status/1354939269404614657/photo/1": 8, "https://twitter.com/weingartende/status/1357023645718228993": 7}
bei trend #lanz
